Repository ohthias/Astro-reimagination, pull requests merged in 2024-09, with the labels that each got.

#4 Ajutes do css base
  Assets/Astro.svg
  CSS/variables.css
  index/index.css
  index/index.html
  index/words.js
Labels: frontend, planning

#5 Merge dos PR
  index.html
  login.css
  login.html
  root css/font.css
  root css/root.css
  root css/teste.css
  root css/variables.css
Labels: duplicate, frontend

#6 Merge geral
  Assets/Astro.svg
  CSS/font.css
  CSS/root.css
  CSS/teste.css
  CSS/variables.css
  index/index.css
  index/index.html
  index/words.js
  login/login.css
  login/login.html
  login/sign.css
  login/sign.html
  login/togglePassword.js
  test/index 3.html
  test/index.html
Labels: duplicate, enhancement, help wanted, frontend, backend, planning

#9 Dao test
  Astro/.gitignore
  Astro/.idea/misc.xml
  Astro/.mvn/wrapper/maven-wrapper.properties
  Astro/mvnw
  Astro/mvnw.cmd
  Astro/pom.xml
  Astro/src/main/java/com/example/Astro/AstroApplication.java
  Astro/src/main/java/com/example/Astro/Controller/HomeController.java
  Astro/src/main/java/com/example/Astro/Model/DAO.java
  Astro/src/main/java/com/example/Astro/Model/UserBeans.java
  Astro/src/main/resources/application.properties
  Astro/src/main/resources/database/Trigger-entre-tabelas.sql
  Astro/src/main/resources/database/View-info-cliente.sql
  Astro/src/main/resources/database/modelo lógico astro.mwb
  Astro/src/main/resources/database/scrpt_astro.sql
  Astro/src/main/resources/database/trigger data criação.sql
  Astro/src/main/resources/static/css/index.css
  Astro/src/main/resources/static/css/login.css
  Astro/src/main/resources/static/css/root/font.css
  Astro/src/main/resources/static/css/root/root.css
  Astro/src/main/resources/static/css/root/teste.css
  Astro/src/main/resources/static/css/root/variables.css
  Astro/src/main/resources/static/css/sign.css
  Astro/src/main/resources/static/favicon/.txt
  Astro/src/main/resources/static/js/redirects.js
  Astro/src/main/resources/static/js/togglePassword.js
  Astro/src/main/resources/static/js/words.js
  Astro/src/main/resources/static/svg/Astro.svg
  Astro/src/main/resources/templates/index.html
  Astro/src/main/resources/templates/login.html
  Astro/src/main/resources/templates/sign.html
  Astro/src/test/java/com/example/Astro/AstroApplicationTests.java
  test/index.html
Labels: bug, documentation, wontfix, frontend, backend

#13 PR database
  .vscode/settings.json
  Astro/src/main/resources/static/css/index.css
  Astro/src/main/resources/static/css/login.css
  Astro/src/main/resources/static/css/root/font.css
  Astro/src/main/resources/static/css/root/root.css
  Astro/src/main/resources/static/css/root/variables.css
  Astro/src/main/resources/static/css/sign.css
  Astro/src/main/resources/static/js/redirects.js
  Astro/src/main/resources/static/js/togglePassword.js
  Astro/src/main/resources/static/sass/index.css.map
  Astro/src/main/resources/static/sass/index.scss
  Astro/src/main/resources/static/sass/sign.css.map
  Astro/src/main/resources/static/sass/sign.scss
  Astro/src/main/resources/templates/home.html
  Astro/src/main/resources/templates/index.html
  Astro/src/main/resources/templates/login.html
  Astro/src/main/resources/templates/sign.html
  style guide/Cadastrar.png
  style guide/Entrar.png
  style guide/Homepage.png
  style guide/Index.png
Labels: frontend, backend

#14 adição de musicas localmente
  Local_songs/localSongs.js
  Local_songs/newSongs/newSong.css
  Local_songs/newSongs/newSong.html
  Local_songs/newSongs/newSongs.js
  Test/APIConsulta.html
  Test/apiMusic.html
  Test/consumoArtista.js
  Test/musics.js
Labels: enhancement, backend, API
